name: NeoLoad-as-code-examples-1_2
includes:
- oauth_workflow.yaml

variables:
- file:
    name: cities
    column_names: ["City"]
    is_first_line_column_names: false
    start_from_line: 1
    delimiter: ","
    path: data/cities.csv
    change_policy: each_iteration
    scope: global
    order: any
    out_of_value: cycle

servers:
- name: app_server
  host: host.docker.internal
  port: 3000

sla_profiles:
- name: sla_internal_api_calls
  thresholds:
  - avg-request-resp-time warn >= 500ms fail >= 1s per test
  - perc-transaction-resp-time (p95) warn >= 300ms fail >= 1200ms per test
  - error-rate warn >= 5% per interval
- name: sla_external_api_calls
  thresholds:
  - avg-request-resp-time warn >= 500ms fail >= 1s per test
  - perc-transaction-resp-time (p95) warn >= 10s fail >= 20s per test
  - error-rate warn >= 5% per interval
- name: sla_static_resources
  thresholds:
  - avg-resp-time warn >= 500ms fail >= 1000ms per interval
- name: sla_internal_api_calls_big_response
  thresholds:
  - perc-transaction-resp-time (p95) warn >= 30s fail >= 60s per test

populations:
- name: popOAuth
  user_paths:
  - name: oauth_workflow

scenarios:
- name: sanityScenario
  populations:
  - name: popOAuth
    rampup_load:
      min_users: 1
      max_users: 5
      increment_users: 1
      increment_every: 5s
      duration: 30s
- name: fullTest
  populations:
  - name: popOAuth
    rampup_load:
      min_users: 1
      max_users: 25
      increment_users: 2
      increment_every: 5s
      duration: 5m
