name: NeoLoad-as-code-module-4
includes:
- paths/geosearch_get_and_put.yaml
- envs/uat/servers.nl.yaml
- envs/uat/variables.nl.yaml
- envs/uat/slas.nl.yaml

# test:
#   one: two three

populations:
- name: pop
  user_paths:
  - name: geosearch_get_and_put

scenarios:
- name: sanityScenario
  populations:
  - name: pop
    rampup_load:
      min_users: 1
      max_users: 5
      increment_users: 1
      increment_every: 2s
      duration: 1m
